name: Testing against Compiler Versions

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
     branches: [ main ]  

jobs:

  compiler-version-testing:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [ 1.20.0, 1.22.3 ]

    services:
      db:
        image: postgres:16.3-alpine3.20
        ports:
          - 5432:5432
        env:
          COMPONENT: ginblog_db
          POSTGRES_USER: gin_blog
          POSTGRES_PASSWORD: secret

    steps:
      - uses: actions/checkout@v4

      - name: Config App
        run: |
          cat .env_sample | sed -re "s/<database_host>/${DB_HOST}/" \
            -re "s/<database_name>/${DB_NAME}/" \
            -re "s/<database_user>/${DB_USER}/" \
            -re "s/<user_password>/${DB_PASSWORD}/" > .env.test
        env:
          # The hostname used to communicate with the PostgreSQL service container
          DB_HOST: localhost
          DB_NAME: gin_blog
          DB_USER: gin_blog
          DB_PASSWORD: secret

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ matrix.go-version }}'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          # The hostname used to communicate with the PostgreSQL service container
          DB_HOST: localhost
